### ISSUE TITLE
Keyboard navigation 

### ISSUE THREAD

**Issue by codingforfun** [rsandz/joplin-calendar#1]
Keyboard navigation in the calender would be great. I think about just moving from day to day with cursor keys. 

(I replaced [rednotebook](https://rednotebook.app) with Joplin for it’s markdown abilities and got it nearly completely replaced by using calendar and journal add-on)

**Comment by rsandz** [comment]
Thanks for the suggestion - I do want to add more keyboards in the future so I'll keep this in mind.

**Comment by rsandz** [comment]
Added in [1.0.0-pre-release-4](https://github.com/rsandz/joplin-calendar/commit/5dd85a34d471242ea4f888ec468fcca135d1186d).
