### ISSUE TITLE
How to create a calendar and an entry

### ISSUE THREAD

**Issue by kklepper** [rsandz/joplin-calendar#10]
Installation was easy. Now I'm stuck. How do I add a new year, month, day, note? I don't see an i icon.

Thanks for any help.

**Comment by kklepper** [comment]
Also: How to close the calender panel?

**Comment by rsandz** [comment]
Hi @kklepper, 
Notes can only be associated for each day so we can't create year or month notes.
When you create a new note normally in Joplin, they will show up on the calendar. (It may take a few seconds to update the calendar though.)

The "🛈" icon is can be found on the top right: 
![image](https://github.com/rsandz/joplin-calendar/assets/39130197/02b0532f-5d1a-4d10-852b-8d47170f329f)

**Comment by kklepper** [comment]
Ah, thanks a lot. I can open and close the calendar panel now. How do I organize it?

I created a note Diary 2024 and a subnote Jan and then clicked the current day 11 so I got an automatic entry 11 in that subnote.

Is that a viable way? Or is the subnote superfluous? After all, every month has a day 11.

I notice that if switch back to the calendar from any note by activating the cal, I get the cal entry, I understand that. Manipulating the i allows to move entries, is that correct?

Compared with my manual attempt this is a great improvement.

![image](https://github.com/rsandz/joplin-calendar/assets/6130319/bb3d8a77-fc63-4294-9976-ca420abff907)

However, I do not understand the creation process. I tried to make a note for a future date, Feb 22, but didn't succeed.

![image](https://github.com/rsandz/joplin-calendar/assets/6130319/4e94ae09-83a2-4c38-99af-21f116a4bd57)

Neither Annastift not 22 are associated to Feb 22. I created a new sub Feb and moved both entries, to no avail. 

Please advise how to work with this tool.

**Comment by kklepper** [comment]
I noticed that the keyboard toggle command does not work, which must be due to my German keyboard. Can I change this?

**Comment by rsandz** [comment]
> I noticed that the keyboard toggle command does not work, which must be due to my German keyboard. Can I change this?

Yup, this can be changed in the keyboard shortcuts.

**Comment by rsandz** [comment]
Regarding creating notes on the calendar:

The file organization doesn't change the date a note shows up in the calendar. 
So moving around notes like "22" and "Annastift" above doesn't actually change the date they show up on.

Let's say, we want to have a note show up on Feb 22, 2024 though.

First, click the "ⓘ" icon. 
Then change the created date like so: 

![image](https://github.com/rsandz/joplin-calendar/assets/39130197/67bd85fd-c0b8-4726-81b7-f5dc29dd06f4)

After that, the note should show up on Feb 22, 2024 on the calendar.

---

We have another issue to add notes directly to calendar dates: #11 
When that is implemented, this will be easier 🙂

**Comment by kklepper** [comment]
Thank you, very much appreciated.
