### ISSUE TITLE
Add ics support

### ISSUE THREAD

**Issue by jjasoncool** [rsandz/joplin-calendar#13]
I hope to enhance support for ICS so that online calendars can be synchronized, reducing the hassle of syncing in multiple places.
Also, if that can sync to nextcloud calendars will better.

**Comment by rsandz** [comment]
Thanks for submitting a suggestion!

I feel that online calendar sync doesn't align with the main use case for this plugin, which is to organize notes on a calendar view.
I also won't have time to support online calendars and integrate with the many ones on the web.

That said, you are free to fork this project to integrate this if you'd like 🙂
