### ISSUE TITLE
High CPU usage/memory leak in Joplin 2.13.5

### ISSUE THREAD

**Issue by runrunrirun** [rsandz/joplin-calendar#18]
For some reason the plugin seems to continuously use CPU and increase memory usage when installed on 2.13 or 2.14 at least on macOS Sonoma 14.3 Intel. This is the only installed plugin. I have ~500 notes in Joplin.

**Comment by rsandz** [comment]
Thank you for the report @runrunrirun!

Do you have additional info on the following?
- Is the high CPU + memory happen transiently? Does it happen only on a specific action or does it persist?
- Is high CPU + memory usage evident when Joplin is started? Or does it take some time for the performance to degrade?
- Would you be willing to share your Joplin vault privately to help with troubleshooting this issue?
-

**Comment by rsandz** [comment]
There was an infinite loop that can occur when there are a lot of notes for a single day. (Caused by pagination logic that didn't actually increment the page). #19 may fix the performance issues seen here.

**Comment by runrunrirun** [comment]
Missed the earlier post, sorry! But it appears to be fixed now, tested in Joplin 2.14.16, memory and CPU use are now stable with this plugin active, thanks!
