### ISSUE TITLE
Mark days with- or without notes differently in the calendar.

### ISSUE THREAD

**Issue by codingforfun** [rsandz/joplin-calendar#2]
Mark days with- or without notes differently in the calendar.

I replaced [rednotebook](https://rednotebook.app) with Joplin for it’s markdown abilities and got it nearly completely replaced by using calendar and journal add-on. 

In rednotebook it is really nice feature to get the empty vs. non-empty days previewed in the calendar differently and jump over empty days in the keyboard navigation.

**Comment by rsandz** [comment]
Thanks for the suggestion. 

Most calendar plugins in other note taking apps have this feature. So this will eventually be added in the future.

**Comment by rsandz** [comment]
Added dots to calendar dates to indicate days where notes were created. 
This feature was added in [1.0.0-pre-release-5](https://github.com/rsandz/joplin-calendar/commit/25c0481f38db7c64b3aeeeb18a023ee515ebde3c).

Still need to implement the jumping between non-empty days via keyboard navigation.

**Comment by rsandz** [comment]
Can jump non-empty days via keyboard navigation now. Will be released in next update.
