### ISSUE TITLE
separate by notebook

### ISSUE THREAD

**Issue by reincha** [rsandz/joplin-calendar#20]
Hi! 
Currently, the calendar displays notes from all notebooks for the selected date. I was wondering if it would be possible to implement a feature where the calendar notes list is separated by notebook? Specifically, if I select a specific notebook in the left notebooks column, it would be great if the calendar could show entries only from that notebook.

**Comment by rsandz** [comment]
Thanks for the suggestion! Definitely something that can be done in the future.

**Comment by rsandz** [comment]
Added a plugin setting to make the calendar only show notes from the selected note book in #25
