### ISSUE TITLE
Toggle the Calendar Button or Menue

### ISSUE THREAD

**Issue by Maghsad** [rsandz/joplin-calendar#6]
Hi,

Thank you for developing this interesting plugin. Could you also consider adding a button to toggle the calendar instead of the Cmd/Ctrl+Shift+` keyboard shortcut?

**Comment by rsandz** [comment]
Thanks for the suggestion @Maghsad!

The calendar can be toggled via the toolbar as well:
![image](https://github.com/rsandz/joplin-calendar/assets/39130197/8e927ba7-953e-4799-ad1e-3face548d272)

If you'd like a button somewhere specifically, please elaborate on your suggestion - thanks!

**Comment by Maghsad** [comment]
Hi Rayan,

Thanks for your swift response. Sure, the menu item is practical. A button could make it even better. I was thinking about adding a button at the top right or near search or new notes.

<a ><img src="https://i.ibb.co/ggGpBC0/SCR-20230826-jqha.png"></a>

**Comment by rsandz** [comment]
Added button in top right of note toolbar to toggle calendar. 
Will be available in next update.

**Comment by Maghsad** [comment]
Hi Rayan,

Thanks for your swift action and for adding this practical feature. 

Cheers
